-- MySQL Script generated by MySQL Workbench
-- Tue Aug  7 16:32:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codigo_barras
-- -----------------------------------------------------
-- Banco de Dados Sistema Gerador de Código de Barras
-- 
DROP SCHEMA IF EXISTS `codigo_barras` ;

-- -----------------------------------------------------
-- Schema codigo_barras
--
-- Banco de Dados Sistema Gerador de Código de Barras
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigo_barras` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `codigo_barras` ;

-- -----------------------------------------------------
-- Table `codigo_barras`.`codigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`codigo` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`codigo` (
  `idcodigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `marca_id` INT NOT NULL,
  `referencia_id` INT NOT NULL,
  `cor_id` INT NOT NULL,
  `tamanho_id` INT NOT NULL,
  PRIMARY KEY (`idcodigo`),
  INDEX `fk_codigo_cor1_idx` (`cor_id` ASC) VISIBLE,
  INDEX `fk_codigo_tamanho1_idx` (`tamanho_id` ASC) VISIBLE,
  INDEX `fk_codigo_referencia1_idx` (`referencia_id` ASC) VISIBLE,
  INDEX `fk_codigo_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_cor1`
    FOREIGN KEY (`cor_id`)
    REFERENCES `codigo_barras`.`cor` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_tamanho1`
    FOREIGN KEY (`tamanho_id`)
    REFERENCES `codigo_barras`.`tamanho` (`idtamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_referencia1`
    FOREIGN KEY (`referencia_id`)
    REFERENCES `codigo_barras`.`referencia` (`idreferecia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `codigo_barras`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigo_barras`.`cor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`cor` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`cor` (
  `idcor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idcor`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `codigo_barras`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`marca` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigo_barras`.`referencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`referencia` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`referencia` (
  `idreferecia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `marca_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`idreferecia`),
  INDEX `fk_referencia_marca_idx` (`marca_id` ASC) VISIBLE,
  INDEX `fk_referencia_tipo1_idx` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_referencia_marca`
    FOREIGN KEY (`marca_id`)
    REFERENCES `codigo_barras`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referencia_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `codigo_barras`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigo_barras`.`tamanho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`tamanho` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`tamanho` (
  `idtamanho` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idtamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigo_barras`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`tipo` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `codigo_barras`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codigo_barras`.`usuario` ;

CREATE TABLE IF NOT EXISTS `codigo_barras`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `mail` VARCHAR(100) NULL,
  `senha` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
